# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"

virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python3-numpy python3-scipy
 - sudo apt-get install python-snappy libsnappy-dev libsnappy1

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test