# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"

virtualenv:
  system_site_packages: false
before_install:
 - sudo apt-get install -qq libatlas-base-dev gfortran
 - sudo apt-get install -qq python3-numpy
 - sudo apt-get install -qq python3-scipy
 - sudo apt-get install -qq cython
 - sudo apt-get install -qq python-snappy libsnappy-dev libsnappy1
 - pip install numpy Cython

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test